### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by MinervaArcher** [PolymerLabs/prpl-ce-firebase#7]
I'm working through the Codelab for this repository and ran into an error when running `firebase login` in terminal:

```
/usr/local/lib/node_modules/firebase-tools/node_modules/google-auto-auth/index.js:10
class Auth {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/requireAuth.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

I set up a project in Firebase Console before running this command, and tried running `npm upgrade` followed by `firebase login`, with the same result. Any ideas?

**Comment by keanulee** [comment]
`class` has been a valid keyword for a while - what version on Node are you using (`node -v`)?
